-- =============================================================================
-- 000_baseline.sql — squashed baseline, generated from the LIVE database 2026-08-23
-- =============================================================================
--
-- WHY THIS EXISTS
-- The live database had 21 applied migrations; only 5 files existed on disk. The
-- schema that built production was largely not in version control. Two concrete
-- dangers, both triggered by anyone running `supabase db reset`:
--
--   1. `user_roles` — the table every auth path depends on (is_admin(),
--      current_app_role(), the Next.js proxy, auth-context) — was created by NO
--      migration file. A rebuilt database had no roles table, so all
--      authorisation broke.
--   2. `001_initial_schema.sql` contained eight `admins_full_access` policies
--      reading `raw_user_meta_data->>'role'`. Users can write their own
--      user_metadata, so that is a self-promotion vector: any account could make
--      itself admin. Verified 0 such policies live (pg_policies), but a reset
--      would have recreated them.
--
-- This file reproduces the live `public` schema. It supersedes 001-005, which are
-- retained only as history and must not be run.
--
-- NOT INCLUDED, and must be recreated by hand:
--   * Vault secrets. The cron jobs at the end read secrets by name from
--     `vault.decrypted_secrets`; the secret VALUES are not here and never should be.
--     Recreate with: select vault.create_secret('<value>', '<name>');
--   * Seed/patient data. Use backend/seed_data.py.
--   * Supabase-managed schemas (auth, storage, realtime, graphql).
--
-- Generated by reading pg_catalog directly (`supabase db dump` is unavailable on
-- this project: the CLI cannot create its login role).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Extensions
-- -----------------------------------------------------------------------------
create extension if not exists pg_stat_statements with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists supabase_vault with schema vault;
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema public;

-- -----------------------------------------------------------------------------
-- 2. Tables (17)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_feedback (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  fhir_resource_id uuid,
  doctor_id uuid NOT NULL,
  action text NOT NULL,
  original_extraction jsonb,
  corrected_extraction jsonb,
  correction_notes text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  user_id uuid,
  user_role text,
  action text NOT NULL,
  resource_type text,
  resource_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.consents (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  purpose text NOT NULL,
  scope text,
  consent_mode text DEFAULT 'verbal'::text,
  granted_at timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.doctors (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  name text NOT NULL,
  email text,
  specialization text,
  phone text,
  created_at timestamp with time zone DEFAULT now(),
  auth_user_id uuid
);

CREATE TABLE IF NOT EXISTS public.drug_brand_mapping (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  brand_name text NOT NULL,
  inn_name text NOT NULL,
  snomed_code text,
  category text
);

CREATE TABLE IF NOT EXISTS public.escalations (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  call_id uuid,
  severity_level text NOT NULL,
  severity text NOT NULL,
  reason text,
  status text DEFAULT 'open'::text,
  assigned_to uuid,
  resolved_at timestamp with time zone,
  resolution_notes text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.fhir_resources (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  call_id uuid,
  resource_type text NOT NULL,
  profile text,
  fhir_json jsonb NOT NULL,
  snomed_codes text[],
  loinc_codes text[],
  review_status text DEFAULT 'pending'::text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  external_ref text
);

CREATE TABLE IF NOT EXISTS public.field_worker_areas (
  user_id uuid NOT NULL,
  village text NOT NULL,
  district text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.health_vitals (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  systolic_bp integer,
  diastolic_bp integer,
  heart_rate integer,
  respiratory_rate integer,
  oxygen_saturation integer,
  temperature numeric(5,2),
  blood_glucose integer,
  height numeric(5,1),
  weight numeric(5,1),
  bmi numeric(4,1),
  bmi_category text,
  waist_circumference numeric(5,1),
  waist_to_height_ratio numeric(6,5),
  perfusion_index numeric(4,1),
  recorded_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.newborns (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  parent_patient_id uuid,
  baby_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text,
  birth_weight_kg numeric,
  birth_hospital text,
  phone text,
  language text DEFAULT 'hindi'::text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.patients (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  abha_id text,
  name text NOT NULL,
  phone text,
  language text DEFAULT 'hindi'::text,
  health_camp text,
  camp_type text,
  risk_level text,
  overall_risk_score numeric(5,2),
  consent_status text DEFAULT 'pending'::text,
  assigned_doctor_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  intake_source text DEFAULT 'health_camp'::text,
  source_incident_id text,
  village text,
  district text,
  auth_user_id uuid,
  occupation text,
  crop_type text,
  last_pesticide_exposure date,
  farmer_registry_id text,
  journey_status text DEFAULT 'screened'::text
);

CREATE TABLE IF NOT EXISTS public.risk_assessments (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  heart_risk_score numeric(5,2),
  heart_risk_level text,
  diabetic_risk_score numeric(5,2),
  diabetic_risk_level text,
  hypertension_risk_score numeric(5,2),
  hypertension_risk_level text,
  overall_risk_category text,
  overall_risk_score numeric(5,2),
  assessed_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.symptoms (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  chest_discomfort text,
  breathlessness text,
  palpitations text,
  fatigue_weakness text,
  dizziness_blackouts text,
  sleep_duration text,
  stress_anxiety text,
  physical_inactivity text,
  diet_quality text,
  family_history text,
  recorded_at timestamp with time zone DEFAULT now()
);

-- The table that was missing from every migration file. Every authorisation path
-- reads it: is_admin(), current_app_role(), the Next.js proxy, auth-context.
-- Deliberately NOT auth.users.raw_user_meta_data, which the user can write.
CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id uuid NOT NULL,
  role text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vaccination_schedules (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  newborn_id uuid,
  vaccine_name text NOT NULL,
  dose_number integer DEFAULT 1,
  due_age text NOT NULL,
  due_date date,
  route_site text,
  remarks text,
  status text DEFAULT 'pending'::text,
  administered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.voice_calls (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  patient_id uuid,
  call_type text NOT NULL,
  use_case text,
  status text DEFAULT 'scheduled'::text,
  language text DEFAULT 'hindi'::text,
  transcript text,
  extracted_data jsonb DEFAULT '{}'::jsonb,
  severity text,
  duration_seconds integer,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  scheduled_for timestamp with time zone,
  workflow_id uuid,
  attempts integer DEFAULT 0 NOT NULL,
  last_error text,
  dispatch_request_id bigint
);

CREATE TABLE IF NOT EXISTS public.workflows (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  name text NOT NULL,
  description text,
  trigger_type text NOT NULL,
  trigger_config jsonb DEFAULT '{}'::jsonb,
  actions jsonb DEFAULT '[]'::jsonb,
  conditions jsonb DEFAULT '{}'::jsonb,
  camp_type text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 3. Constraints — primary keys, unique, checks, then foreign keys last
-- -----------------------------------------------------------------------------
-- `when others` on purpose, not the narrower duplicate_table/duplicate_object:
-- re-adding an existing PRIMARY KEY raises 42P16 ("multiple primary keys ... not
-- allowed"), which neither of those handlers catches, so a second run of this file
-- would abort. Verified against live Postgres 17.
do $$ begin
  -- primary keys
  alter table public.ai_feedback add constraint ai_feedback_pkey PRIMARY KEY (id);
  alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (id);
  alter table public.consents add constraint consents_pkey PRIMARY KEY (id);
  alter table public.doctors add constraint doctors_pkey PRIMARY KEY (id);
  alter table public.drug_brand_mapping add constraint drug_brand_mapping_pkey PRIMARY KEY (id);
  alter table public.escalations add constraint escalations_pkey PRIMARY KEY (id);
  alter table public.fhir_resources add constraint fhir_resources_pkey PRIMARY KEY (id);
  alter table public.field_worker_areas add constraint field_worker_areas_pkey PRIMARY KEY (user_id, village);
  alter table public.health_vitals add constraint health_vitals_pkey PRIMARY KEY (id);
  alter table public.newborns add constraint newborns_pkey PRIMARY KEY (id);
  alter table public.patients add constraint patients_pkey PRIMARY KEY (id);
  alter table public.risk_assessments add constraint risk_assessments_pkey PRIMARY KEY (id);
  alter table public.symptoms add constraint symptoms_pkey PRIMARY KEY (id);
  alter table public.user_roles add constraint user_roles_pkey PRIMARY KEY (user_id);
  alter table public.vaccination_schedules add constraint vaccination_schedules_pkey PRIMARY KEY (id);
  alter table public.voice_calls add constraint voice_calls_pkey PRIMARY KEY (id);
  alter table public.workflows add constraint workflows_pkey PRIMARY KEY (id);
exception when others then null; end $$;

do $$ begin
  alter table public.doctors add constraint doctors_email_key UNIQUE (email);
exception when others then null; end $$;
do $$ begin
  alter table public.patients add constraint patients_abha_id_key UNIQUE (abha_id);
exception when others then null; end $$;

-- risk_level canonical form. See the trigger in section 6: writers historically
-- disagreed on case ('high' vs 'High') and every desktop reader compares exactly,
-- so a high-risk patient silently vanished from high-risk counts.
do $$ begin
  alter table public.patients add constraint patients_risk_level_canonical
    CHECK (((risk_level IS NULL) OR (risk_level = ANY (ARRAY['High'::text, 'Moderate'::text, 'Low'::text, 'Unknown'::text]))));
exception when others then null; end $$;
do $$ begin
  alter table public.user_roles add constraint user_roles_role_check
    CHECK ((role = ANY (ARRAY['admin'::text, 'doctor'::text, 'asha'::text, 'patient'::text, 'farmer'::text])));
exception when others then null; end $$;

-- foreign keys. One block per table so a single pre-existing FK does not skip the
-- rest — a shared block aborts at the first duplicate and silently leaves the
-- remainder unapplied, which is how you get a schema that looks complete.
do $$ begin alter table public.ai_feedback add constraint ai_feedback_fhir_resource_id_fkey FOREIGN KEY (fhir_resource_id) REFERENCES fhir_resources(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.consents add constraint consents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.doctors add constraint doctors_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL; exception when others then null; end $$;
do $$ begin alter table public.escalations add constraint escalations_call_id_fkey FOREIGN KEY (call_id) REFERENCES voice_calls(id) ON DELETE SET NULL; exception when others then null; end $$;
do $$ begin alter table public.escalations add constraint escalations_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.fhir_resources add constraint fhir_resources_call_id_fkey FOREIGN KEY (call_id) REFERENCES voice_calls(id) ON DELETE SET NULL; exception when others then null; end $$;
do $$ begin alter table public.fhir_resources add constraint fhir_resources_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.field_worker_areas add constraint field_worker_areas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.health_vitals add constraint health_vitals_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.newborns add constraint newborns_parent_patient_id_fkey FOREIGN KEY (parent_patient_id) REFERENCES patients(id); exception when others then null; end $$;
do $$ begin alter table public.patients add constraint patients_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL; exception when others then null; end $$;
do $$ begin alter table public.risk_assessments add constraint risk_assessments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.symptoms add constraint symptoms_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.user_roles add constraint user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.vaccination_schedules add constraint vaccination_schedules_newborn_id_fkey FOREIGN KEY (newborn_id) REFERENCES newborns(id); exception when others then null; end $$;
do $$ begin alter table public.voice_calls add constraint voice_calls_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE; exception when others then null; end $$;
do $$ begin alter table public.voice_calls add constraint voice_calls_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE SET NULL; exception when others then null; end $$;

-- -----------------------------------------------------------------------------
-- 4. Indexes (constraint-backed indexes omitted — created implicitly above)
-- -----------------------------------------------------------------------------
-- The unique ones are load-bearing: they arbitrate ON CONFLICT in the acute->
-- continuity seam and the recovery scheduler. A partial index CANNOT arbitrate
-- ON CONFLICT, which is why uq_voice_calls_protocol_slot is unconditional.
CREATE INDEX IF NOT EXISTS idx_audit_log_time ON public.audit_log USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_doctors_auth_user ON public.doctors USING btree (auth_user_id) WHERE (auth_user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_drug_brand ON public.drug_brand_mapping USING btree (brand_name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_drug_brand_name ON public.drug_brand_mapping USING btree (brand_name);
CREATE INDEX IF NOT EXISTS idx_escalations_severity ON public.escalations USING btree (severity);
CREATE INDEX IF NOT EXISTS idx_escalations_status ON public.escalations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_fhir_patient ON public.fhir_resources USING btree (patient_id);
CREATE INDEX IF NOT EXISTS idx_fhir_review ON public.fhir_resources USING btree (review_status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_fhir_external_ref ON public.fhir_resources USING btree (patient_id, resource_type, external_ref);
CREATE INDEX IF NOT EXISTS idx_patients_camp ON public.patients USING btree (health_camp);
CREATE INDEX IF NOT EXISTS idx_patients_camp_type ON public.patients USING btree (camp_type);
CREATE INDEX IF NOT EXISTS idx_patients_district ON public.patients USING btree (district) WHERE (district IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_patients_journey ON public.patients USING btree (journey_status);
CREATE INDEX IF NOT EXISTS idx_patients_occupation ON public.patients USING btree (occupation) WHERE (occupation IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_patients_risk ON public.patients USING btree (risk_level);
CREATE INDEX IF NOT EXISTS idx_patients_source_incident ON public.patients USING btree (source_incident_id) WHERE (source_incident_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_patients_village ON public.patients USING btree (village) WHERE (village IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_patients_auth_user ON public.patients USING btree (auth_user_id) WHERE (auth_user_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_patients_phone ON public.patients USING btree (phone);
CREATE INDEX IF NOT EXISTS idx_voice_calls_due ON public.voice_calls USING btree (scheduled_for) WHERE (status = 'scheduled'::text);
CREATE INDEX IF NOT EXISTS idx_voice_calls_patient ON public.voice_calls USING btree (patient_id);
CREATE INDEX IF NOT EXISTS idx_voice_calls_status ON public.voice_calls USING btree (status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_voice_calls_advisory ON public.voice_calls USING btree (patient_id, ((extracted_data ->> 'advisory_key'::text))) WHERE (call_type = 'advisory'::text);
CREATE UNIQUE INDEX IF NOT EXISTS uq_voice_calls_protocol_slot ON public.voice_calls USING btree (patient_id, workflow_id, scheduled_for);
CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_name ON public.workflows USING btree (name);

-- -----------------------------------------------------------------------------
-- 5. Functions (11) — BEFORE policies, which call them
-- -----------------------------------------------------------------------------
-- All the auth helpers are SECURITY DEFINER on purpose: they break the policy
-- recursion that would otherwise occur when a patients policy needs to read
-- patients. They read public.user_roles, never auth.users.raw_user_meta_data,
-- because a user can write their own metadata and so it cannot decide anything.

CREATE OR REPLACE FUNCTION public.current_app_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT role FROM user_roles WHERE user_id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin');
$function$;

CREATE OR REPLACE FUNCTION public.asha_villages()
 RETURNS SETOF text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT village FROM field_worker_areas WHERE user_id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.visible_patient_ids()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p.id
  FROM patients p
  WHERE public.is_admin()
     OR (public.current_app_role() = 'doctor'
         AND p.assigned_doctor_id IN (SELECT d.id FROM doctors d WHERE d.auth_user_id = auth.uid()))
     OR (public.current_app_role() = 'asha'
         AND p.village IN (SELECT public.asha_villages()))
     OR p.auth_user_id = auth.uid();
$function$;

-- An ASHA-registered patient has no assigned_doctor_id, so visible_patient_ids()
-- hid their escalation from every doctor: the alert was written and read by nobody
-- but admin. Scoped to escalations only — widening visible_patient_ids() itself
-- would expose every unassigned patient's full record to every doctor.
CREATE OR REPLACE FUNCTION public.escalation_visible(p_patient_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    p_patient_id in (select public.visible_patient_ids())
    or (
      public.current_app_role() = 'doctor'
      and exists (
        select 1 from patients p
        where p.id = p_patient_id and p.assigned_doctor_id is null
      )
    );
$function$;

-- Reads escalations ONLY, never patients, so it cannot recurse through the
-- patients_select_triage_pool policy that calls it.
CREATE OR REPLACE FUNCTION public.in_triage_pool(p_patient_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from escalations e
    where e.patient_id = p_patient_id
      and e.status = 'open'
      and e.assigned_to is null
  );
$function$;

CREATE OR REPLACE FUNCTION public.canonical_risk_level(v text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select case
    when v is null or btrim(v) = '' then null
    when lower(btrim(v)) like 'high%'     then 'High'
    when lower(btrim(v)) like 'critical%' then 'High'
    when lower(btrim(v)) like 'mod%'      then 'Moderate'
    when lower(btrim(v)) like 'medium%'   then 'Moderate'
    when lower(btrim(v)) like 'low%'      then 'Low'
    else 'Unknown'
  end;
$function$;

CREATE OR REPLACE FUNCTION public.patients_normalise_risk_level()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.risk_level := public.canonical_risk_level(new.risk_level);
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.heat_risk_cohort(p_district text)
 RETURNS TABLE(patient_id uuid, name text, phone text, language text, occupation text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p.id, p.name, p.phone, p.language, p.occupation
  FROM patients p
  WHERE p.district = p_district
    AND p.phone IS NOT NULL
    AND (
      p.occupation IN ('farmer','field_labour','construction','daily_wage')
      OR p.crop_type IS NOT NULL
    );
$function$;

-- Called by the pg_cron job at the end of this file. Reads its credentials from
-- vault by name; the secret VALUES are not in this migration and must be created
-- separately (see the header).
CREATE OR REPLACE FUNCTION public.place_due_recovery_calls(batch_size integer DEFAULT 25)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions', 'net'
AS $function$
DECLARE
  v_url text;
  v_key text;
  v_req bigint;
  r     record;
  n     int := 0;
BEGIN
  SELECT decrypted_secret INTO v_url FROM vault.decrypted_secrets WHERE name = 'project_url';
  SELECT decrypted_secret INTO v_key FROM vault.decrypted_secrets WHERE name = 'edge_function_key';

  IF v_url IS NULL OR v_key IS NULL THEN
    RAISE NOTICE 'vault secrets project_url / edge_function_key not set - skipping';
    RETURN 0;
  END IF;

  FOR r IN
    SELECT vc.id, vc.patient_id, vc.language, vc.call_type,
           p.name AS patient_name, p.phone
    FROM voice_calls vc
    JOIN patients p ON p.id = vc.patient_id
    WHERE vc.status = 'scheduled'
      AND vc.scheduled_for IS NOT NULL
      AND vc.scheduled_for <= now()
      AND p.phone IS NOT NULL
    ORDER BY vc.scheduled_for
    LIMIT batch_size
    FOR UPDATE OF vc SKIP LOCKED
  LOOP
    -- 120s, not 5s: the function holds the connection open for the whole ring.
    SELECT net.http_post(
      url     := v_url || '/functions/v1/start-voice-call',
      headers := jsonb_build_object(
                   'Content-Type', 'application/json',
                   'Authorization', 'Bearer ' || v_key
                 ),
      body    := jsonb_build_object(
                   'patient_id',   r.patient_id,
                   'patient_name', r.patient_name,
                   'language',     r.language,
                   'call_type',    COALESCE(r.call_type, 'recovery'),
                   'phone_number', r.phone
                 ),
      timeout_milliseconds := 120000
    ) INTO v_req;

    UPDATE voice_calls
       SET status = 'in_progress',
           started_at = now(),
           dispatch_request_id = v_req
     WHERE id = r.id;

    n := n + 1;
  END LOOP;

  RETURN n;
END;
$function$;

-- Patient safety: an ambiguous dispatch outcome is terminal, never auto-redialed.
-- The phone may already have rung, and calling a recovering patient twice is worse
-- than missing one call that a human can review.
CREATE OR REPLACE FUNCTION public.reconcile_stuck_calls(stale_after interval DEFAULT '00:15:00'::interval, max_attempts integer DEFAULT 3)
 RETURNS TABLE(completed integer, requeued integer, failed integer, in_flight integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions', 'net'
AS $function$
DECLARE
  r           record;
  v_status    int;
  v_timedout  boolean;
  v_err       text;
  v_found     boolean;
  v_done      int := 0;
  v_requeue   int := 0;
  v_failed    int := 0;
  v_inflight  int := 0;
BEGIN
  FOR r IN
    SELECT id, attempts, started_at, dispatch_request_id
    FROM voice_calls
    WHERE status = 'in_progress'
    FOR UPDATE SKIP LOCKED
  LOOP
    v_status := NULL; v_timedout := NULL; v_err := NULL; v_found := false;

    IF r.dispatch_request_id IS NOT NULL THEN
      SELECT status_code, timed_out, error_msg, true
        INTO v_status, v_timedout, v_err, v_found
        FROM net._http_response
       WHERE id = r.dispatch_request_id;
    END IF;

    IF v_found AND v_status BETWEEN 200 AND 299 THEN
      UPDATE voice_calls
         SET status = 'completed', ended_at = COALESCE(ended_at, now()), last_error = NULL
       WHERE id = r.id;
      v_done := v_done + 1;

    ELSIF v_found AND v_status >= 400 THEN
      -- The function rejected the request, so no call was placed. Safe to retry.
      IF r.attempts < max_attempts THEN
        UPDATE voice_calls
           SET status = 'scheduled', attempts = attempts + 1, started_at = NULL,
               dispatch_request_id = NULL,
               last_error = 'dispatch returned HTTP ' || v_status || ' - requeued'
         WHERE id = r.id;
        v_requeue := v_requeue + 1;
      ELSE
        UPDATE voice_calls
           SET status = 'failed', attempts = attempts + 1,
               last_error = 'abandoned after ' || max_attempts
                            || ' attempts (last HTTP ' || v_status || ')'
         WHERE id = r.id;
        v_failed := v_failed + 1;
      END IF;

    ELSIF v_found AND COALESCE(v_timedout, false) THEN
      -- Deliberately terminal. The phone may have rung; do not call again.
      UPDATE voice_calls
         SET status = 'failed',
             last_error = 'dispatch timed out - outcome unknown, not retried to avoid a '
                          || 'duplicate call to the patient. Review manually. ('
                          || COALESCE(v_err, '') || ')'
       WHERE id = r.id;
      v_failed := v_failed + 1;

    ELSE
      -- No response recorded yet: still ringing, or pg_net pruned the row.
      IF r.started_at IS NULL OR r.started_at > now() - stale_after THEN
        v_inflight := v_inflight + 1;
      ELSE
        UPDATE voice_calls
           SET status = 'failed',
               last_error = 'no dispatch response recorded within ' || stale_after::text
                            || ' - outcome unknown, not retried'
         WHERE id = r.id;
        v_failed := v_failed + 1;
      END IF;
    END IF;
  END LOOP;

  RETURN QUERY SELECT v_done, v_requeue, v_failed, v_inflight;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 6. Triggers
-- -----------------------------------------------------------------------------
drop trigger if exists trg_patients_normalise_risk_level on public.patients;
create trigger trg_patients_normalise_risk_level
  before insert or update of risk_level on public.patients
  for each row execute function public.patients_normalise_risk_level();

-- -----------------------------------------------------------------------------
-- 7. View (1) — security_invoker so the caller's RLS applies, not the owner's
-- -----------------------------------------------------------------------------
create or replace view public.district_occupational_health
  with (security_invoker = true) as
 SELECT p.district,
    p.village,
    p.occupation,
    p.crop_type,
    count(*) AS patients,
    count(*) FILTER (WHERE p.last_pesticide_exposure > (CURRENT_DATE - 30)) AS pesticide_exposed_30d,
    count(*) FILTER (WHERE p.risk_level = 'High'::text) AS high_risk,
    count(*) FILTER (WHERE s.breathlessness IS NOT NULL AND (lower(s.breathlessness) <> ALL (ARRAY['none'::text, 'no'::text, 'never'::text, ''::text]))) AS breathlessness,
    count(*) FILTER (WHERE s.chest_discomfort IS NOT NULL AND (lower(s.chest_discomfort) <> ALL (ARRAY['none'::text, 'no'::text, 'never'::text, ''::text]))) AS chest_discomfort,
    count(*) FILTER (WHERE s.dizziness_blackouts IS NOT NULL AND (lower(s.dizziness_blackouts) <> ALL (ARRAY['none'::text, 'no'::text, 'never'::text, ''::text]))) AS dizziness,
    count(*) FILTER (WHERE s.fatigue_weakness IS NOT NULL AND (lower(s.fatigue_weakness) <> ALL (ARRAY['none'::text, 'no'::text, 'never'::text, ''::text]))) AS fatigue
   FROM patients p
     LEFT JOIN LATERAL ( SELECT s2.chest_discomfort,
            s2.breathlessness,
            s2.fatigue_weakness,
            s2.dizziness_blackouts
           FROM symptoms s2
          WHERE s2.patient_id = p.id
          ORDER BY s2.recorded_at DESC NULLS LAST
         LIMIT 1) s ON true
  WHERE p.district IS NOT NULL
  GROUP BY p.district, p.village, p.occupation, p.crop_type;

-- -----------------------------------------------------------------------------
-- 8. Row Level Security — enabled on all 17 tables
-- -----------------------------------------------------------------------------
alter table public.ai_feedback enable row level security;
alter table public.audit_log enable row level security;
alter table public.consents enable row level security;
alter table public.doctors enable row level security;
alter table public.drug_brand_mapping enable row level security;
alter table public.escalations enable row level security;
alter table public.fhir_resources enable row level security;
alter table public.field_worker_areas enable row level security;
alter table public.health_vitals enable row level security;
alter table public.newborns enable row level security;
alter table public.patients enable row level security;
alter table public.risk_assessments enable row level security;
alter table public.symptoms enable row level security;
alter table public.user_roles enable row level security;
alter table public.vaccination_schedules enable row level security;
alter table public.voice_calls enable row level security;
alter table public.workflows enable row level security;

-- -----------------------------------------------------------------------------
-- 9. Policies (48)
-- -----------------------------------------------------------------------------
-- NOTE: the eight `admins_full_access` policies from the old 001_initial_schema.sql
-- are deliberately absent. They read auth.users.raw_user_meta_data->>'role', which
-- the user can write to, so any account could grant itself admin. Confirmed 0 such
-- policies live on 2026-08-23. Admin is decided by public.user_roles via is_admin().

drop policy if exists ai_feedback_insert on public.ai_feedback;
create policy ai_feedback_insert on public.ai_feedback for insert to authenticated
  with check (((current_app_role() = ANY (ARRAY['doctor'::text, 'admin'::text])) OR is_admin()));
drop policy if exists ai_feedback_select on public.ai_feedback;
create policy ai_feedback_select on public.ai_feedback for select to authenticated
  using ((fhir_resource_id IN ( SELECT f.id
   FROM fhir_resources f
  WHERE (f.patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))));
drop policy if exists audit_insert on public.audit_log;
create policy audit_insert on public.audit_log for insert to authenticated
  with check (true);
drop policy if exists audit_select on public.audit_log;
create policy audit_select on public.audit_log for select to authenticated
  using (is_admin());
drop policy if exists consents_delete on public.consents;
create policy consents_delete on public.consents for delete to authenticated
  using (is_admin());
drop policy if exists consents_insert on public.consents;
create policy consents_insert on public.consents for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists consents_select on public.consents;
create policy consents_select on public.consents for select to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists consents_update on public.consents;
create policy consents_update on public.consents for update to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists doctors_write on public.doctors;
create policy doctors_write on public.doctors for all to authenticated
  using (is_admin())
  with check (is_admin());
drop policy if exists doctors_select on public.doctors;
create policy doctors_select on public.doctors for select to authenticated
  using (true);
drop policy if exists drug_mapping_read on public.drug_brand_mapping;
create policy drug_mapping_read on public.drug_brand_mapping for select to public
  using (true);
drop policy if exists escalations_delete on public.escalations;
create policy escalations_delete on public.escalations for delete to authenticated
  using (is_admin());
drop policy if exists escalations_insert on public.escalations;
create policy escalations_insert on public.escalations for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists escalations_select on public.escalations;
create policy escalations_select on public.escalations for select to authenticated
  using (escalation_visible(patient_id));
drop policy if exists escalations_update on public.escalations;
create policy escalations_update on public.escalations for update to authenticated
  using (escalation_visible(patient_id))
  with check (escalation_visible(patient_id));
drop policy if exists fhir_resources_delete on public.fhir_resources;
create policy fhir_resources_delete on public.fhir_resources for delete to authenticated
  using (is_admin());
drop policy if exists fhir_resources_insert on public.fhir_resources;
create policy fhir_resources_insert on public.fhir_resources for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists fhir_resources_select on public.fhir_resources;
create policy fhir_resources_select on public.fhir_resources for select to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists fhir_resources_update on public.fhir_resources;
create policy fhir_resources_update on public.fhir_resources for update to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists field_areas_read_own on public.field_worker_areas;
create policy field_areas_read_own on public.field_worker_areas for select to authenticated
  using ((user_id = auth.uid()));
drop policy if exists health_vitals_delete on public.health_vitals;
create policy health_vitals_delete on public.health_vitals for delete to authenticated
  using (is_admin());
drop policy if exists health_vitals_insert on public.health_vitals;
create policy health_vitals_insert on public.health_vitals for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists health_vitals_select on public.health_vitals;
create policy health_vitals_select on public.health_vitals for select to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists health_vitals_update on public.health_vitals;
create policy health_vitals_update on public.health_vitals for update to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists newborns_write on public.newborns;
create policy newborns_write on public.newborns for all to authenticated
  using ((parent_patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((parent_patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists newborns_select on public.newborns;
create policy newborns_select on public.newborns for select to authenticated
  using ((parent_patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists patients_delete on public.patients;
create policy patients_delete on public.patients for delete to authenticated
  using (is_admin());
drop policy if exists patients_insert on public.patients;
create policy patients_insert on public.patients for insert to authenticated
  with check ((is_admin() OR (current_app_role() = 'asha'::text)));
drop policy if exists patients_select on public.patients;
create policy patients_select on public.patients for select to authenticated
  using ((id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
-- Additive second SELECT policy (policies for the same command OR together): lets a
-- doctor see the patient behind an unclaimed escalation, so the triage queue can name
-- them instead of rendering "Unknown". Drops out once the alert is claimed.
drop policy if exists patients_select_triage_pool on public.patients;
create policy patients_select_triage_pool on public.patients for select to authenticated
  using (((current_app_role() = 'doctor'::text) AND in_triage_pool(id)));
drop policy if exists patients_update on public.patients;
create policy patients_update on public.patients for update to authenticated
  using ((id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((is_admin() OR (current_app_role() = ANY (ARRAY['asha'::text, 'doctor'::text]))));
drop policy if exists risk_assessments_delete on public.risk_assessments;
create policy risk_assessments_delete on public.risk_assessments for delete to authenticated
  using (is_admin());
drop policy if exists risk_assessments_insert on public.risk_assessments;
create policy risk_assessments_insert on public.risk_assessments for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists risk_assessments_select on public.risk_assessments;
create policy risk_assessments_select on public.risk_assessments for select to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists risk_assessments_update on public.risk_assessments;
create policy risk_assessments_update on public.risk_assessments for update to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists symptoms_delete on public.symptoms;
create policy symptoms_delete on public.symptoms for delete to authenticated
  using (is_admin());
drop policy if exists symptoms_insert on public.symptoms;
create policy symptoms_insert on public.symptoms for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists symptoms_select on public.symptoms;
create policy symptoms_select on public.symptoms for select to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists symptoms_update on public.symptoms;
create policy symptoms_update on public.symptoms for update to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
-- Read-own only. Nobody can grant themselves a role through the API; roles are
-- assigned out of band. This is the whole reason user_roles exists.
drop policy if exists user_roles_read_own on public.user_roles;
create policy user_roles_read_own on public.user_roles for select to authenticated
  using ((user_id = auth.uid()));
drop policy if exists vaccination_write on public.vaccination_schedules;
create policy vaccination_write on public.vaccination_schedules for all to authenticated
  using ((newborn_id IN ( SELECT n.id
   FROM newborns n
  WHERE (n.parent_patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))))
  with check ((newborn_id IN ( SELECT n.id
   FROM newborns n
  WHERE (n.parent_patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))));
drop policy if exists vaccination_select on public.vaccination_schedules;
create policy vaccination_select on public.vaccination_schedules for select to authenticated
  using ((newborn_id IN ( SELECT n.id
   FROM newborns n
  WHERE (n.parent_patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))));
drop policy if exists voice_calls_delete on public.voice_calls;
create policy voice_calls_delete on public.voice_calls for delete to authenticated
  using (is_admin());
drop policy if exists voice_calls_insert on public.voice_calls;
create policy voice_calls_insert on public.voice_calls for insert to authenticated
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists voice_calls_select on public.voice_calls;
create policy voice_calls_select on public.voice_calls for select to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists voice_calls_update on public.voice_calls;
create policy voice_calls_update on public.voice_calls for update to authenticated
  using ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)))
  with check ((patient_id IN ( SELECT visible_patient_ids() AS visible_patient_ids)));
drop policy if exists workflows_write on public.workflows;
create policy workflows_write on public.workflows for all to authenticated
  using (is_admin())
  with check (is_admin());
drop policy if exists workflows_select on public.workflows;
create policy workflows_select on public.workflows for select to authenticated
  using (true);

-- -----------------------------------------------------------------------------
-- 10. Grants — anon gets nothing but the drug reference table
-- -----------------------------------------------------------------------------
-- GRANTs are checked BEFORE RLS, so revoking anon is a second, independent lock:
-- even a policy bug cannot expose patient rows to an unauthenticated caller. The
-- live state has anon holding exactly one privilege: SELECT on drug_brand_mapping,
-- which contains no patient data.
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;
grant select on public.drug_brand_mapping to anon;

grant all on all tables in schema public to authenticated, service_role;
grant all on all sequences in schema public to authenticated, service_role;

-- Stop future migrations silently re-granting anon. Without this, any later
-- CREATE TABLE inherits the default privileges and anon regains access.
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public revoke all on sequences from anon;

-- -----------------------------------------------------------------------------
-- 11. Cron jobs (2)
-- -----------------------------------------------------------------------------
-- Off-the-minute schedules on purpose: :02/:07/... and :04/:14/... rather than :00,
-- so the two jobs never contend and neither lands on the busiest tick.
-- REQUIRES the vault secrets named in place_due_recovery_calls() above:
--   select vault.create_secret('https://<ref>.supabase.co', 'project_url');
--   select vault.create_secret('<edge function key>',       'edge_function_key');
-- Without them the job logs a NOTICE and returns 0 rather than failing.
select cron.unschedule('place-due-recovery-calls')
  where exists (select 1 from cron.job where jobname = 'place-due-recovery-calls');
select cron.schedule(
  'place-due-recovery-calls',
  '2,7,12,17,22,27,32,37,42,47,52,57 * * * *',
  $CRON$SELECT public.place_due_recovery_calls();$CRON$
);

select cron.unschedule('reconcile-stuck-calls')
  where exists (select 1 from cron.job where jobname = 'reconcile-stuck-calls');
select cron.schedule(
  'reconcile-stuck-calls',
  '4,14,24,34,44,54 * * * *',
  $CRON$SELECT public.reconcile_stuck_calls();$CRON$
);

-- -----------------------------------------------------------------------------
-- 12. Workflow definitions (8) — CONFIGURATION, not sample data
-- -----------------------------------------------------------------------------
-- These are load-bearing. `incident-complete` looks up "Post-Discharge Recovery"
-- by name to enrol a patient, and voice_calls.workflow_id is a FK to these rows —
-- uq_voice_calls_protocol_slot (patient_id, workflow_id, scheduled_for) is what
-- makes recovery enrolment idempotent. A database rebuilt without them has a
-- working schema and a dead seam, which is why they belong in the migration rather
-- than in seed_data.py. ON CONFLICT (name) keeps re-running safe.
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Chronic Monthly Check-in', 'Monthly voice call for chronic disease patients', 'time_based', '{"interval_days": 30}'::jsonb, '[{"type": "voice_call", "template": "chronic_checkin"}, {"if": "readings_abnormal", "type": "escalate"}]'::jsonb, '{"overall_risk_category": ["Moderate", "High"]}'::jsonb, null, true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Elderly Care - Weekly', 'Weekly check-in for old age home patients', 'time_based', '{"interval_days": 7}'::jsonb, '[{"type": "voice_call", "template": "elderly_checkin"}, {"if": "any_concern", "type": "escalate"}]'::jsonb, '{}'::jsonb, 'elderly', true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Heat Advisory', 'District heat-stress advisory calls to outdoor workers, triggered by weather threshold', 'event_based', '{"call_hour_utc": 3, "call_minute_utc": 30, "consecutive_days": 2, "threshold_celsius": 40}'::jsonb, '[{"type": "voice_call", "template": "heat_advisory"}]'::jsonb, '{"occupation": ["farmer", "field_labour", "construction", "daily_wage"]}'::jsonb, null, true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Newborn Vaccination Reminders', 'Automated voice reminders for upcoming vaccinations based on NIP India schedule (0-12 months). Calls parents 3 days before due date.', 'time_based', '{"schedule": "vaccination_calendar", "days_before_due": 3}'::jsonb, '[{"type": "voice_call", "template": "newborn_vaccination"}, {"type": "whatsapp", "template": "vaccination_reminder"}]'::jsonb, '{"has_newborn": true}'::jsonb, 'vaccination', true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('OPD to IPD Escalation', 'Automated follow-up calls after OPD visit to detect symptom deterioration and escalate to IPD admission if needed.', 'event_based', '{"event": "opd_visit_completed", "delay_hours": 24}'::jsonb, '[{"type": "voice_call", "template": "opd_to_ipd"}, {"type": "escalation", "severity": "HIGH", "condition": "symptoms_worsening"}]'::jsonb, '{"has_opd_visit": true}'::jsonb, null, true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Post-Discharge Recovery', 'Automated recovery protocol calls on Day 1, 3, 7, 14, 30', 'time_based', '{"schedule_days": [1, 3, 7, 14, 30]}'::jsonb, '[{"type": "voice_call", "template": "recovery_check"}, {"if": "medication_missed >= 3", "type": "escalate"}]'::jsonb, '{}'::jsonb, null, true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Recovery Protocol Monitoring', 'Post-discharge recovery calls on Day 1, 3, 7, 14, 30 to monitor wound healing, medication adherence, and detect complications early.', 'time_based', '{"trigger": "discharge_date", "schedule_days": [1, 3, 7, 14, 30]}'::jsonb, '[{"type": "voice_call", "template": "recovery_protocol"}, {"type": "escalation", "condition": "wound_infection OR medication_missed_3days"}]'::jsonb, '{"is_discharged": true}'::jsonb, null, true) on conflict (name) do nothing;
insert into public.workflows (name, description, trigger_type, trigger_config, actions, conditions, camp_type, is_active) values ('Screening to OPD Follow-up', 'Call HIGH risk patients from health camps within 24hrs', 'risk_based', '{"risk_level": "High", "delay_hours": 24}'::jsonb, '[{"type": "voice_call", "template": "screening_followup"}, {"if": "severity >= HIGH", "type": "escalate"}]'::jsonb, '{"overall_risk_category": "High"}'::jsonb, null, true) on conflict (name) do nothing;

-- =============================================================================
-- End of baseline. Verified against the live database 2026-08-23:
--   17 tables · 48 policies · 11 functions · 1 view · 1 trigger · 2 cron jobs
--   8 workflow rows · user_roles present · 0 raw_user_meta_data policies
-- After running this on a fresh database you must still:
--   1. create the two vault secrets (see section 11)
--   2. insert your own user_roles rows — nobody can self-assign a role
--   3. seed patient data if wanted: python backend/seed_data.py
-- =============================================================================




